- name: Enforce firewall rules
  hosts: web

- tasks: 
  - name: firewalld denies http service
    firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: yes

  - name: firewalld permits https service
    firewalld:
      service: https
      permanent: true
      state: enabled
      immediate: yes
  
  - name: firewalld permits dhcpv6-client service
    firewalld:
    service: dhcpv6-client
    permanent: true
    state: enabled
    immediate: yes

  - name: firewalld permits cockpit service
    firewalld:
      service: cockpit
      permanent: true
      state: enabled
      immediate: yes
      
  - name: firewalld permits ssh service
    firewalld:
      service: ssh
      permanent: true
      state: enabled
      immediate: yes
